// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://oajnupvjgnvhwprwzuix.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9ham51cHZqZ252aHdwcnd6dWl4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3Njk1NjUwNzcsImV4cCI6MjA4NTE0MTA3N30.2Lmt5NJzrDDgDFDbQEvjSprF980jcU8iiD0vgKwiQyA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});